# Generated by Django 4.1.7 on 2023-03-15 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
