# Generated by Django 4.1.7 on 2023-03-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_book', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
