# Generated by Django 4.1.7 on 2023-03-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msg', '0003_alter_message_sender_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('min_age_required', models.IntegerField(default=13)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msg.files')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msg.message')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(to='chatrooms.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msg.files')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msg.message')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
