# Generated by Django 4.1.7 on 2023-03-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_alter_message_sender_files'),
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.CharField(blank=True, default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='msg.files'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='msg.message'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='chatrooms.topic'),
        ),
    ]
