# Generated by Django 4.1.7 on 2023-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_alter_chatroom_description_alter_chatroom_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='topics',
            field=models.ManyToManyField(to='chatrooms.topic'),
        ),
    ]
