# Generated by Django 4.1.7 on 2023-03-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_alter_message_sender_files'),
        ('chatrooms', '0003_alter_chatroom_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='msg.files'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='msg.message'),
        ),
    ]
