# Generated by Django 4.1.7 on 2023-03-18 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0003_remove_chatmessage_chat_remove_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatroomMessage',
            new_name='Message',
        ),
    ]
