# Generated by Django 4.1.7 on 2023-03-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_alter_message_sender_files'),
        ('chatrooms', '0004_alter_chat_files_alter_chat_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='files',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='files',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='files',
            field=models.ManyToManyField(to='msg.files'),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(to='msg.message'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='files',
            field=models.ManyToManyField(to='msg.files'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(to='msg.message'),
        ),
    ]
