# Generated by Django 4.1.7 on 2023-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0005_alter_message_chatroom_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
