# Generated by Django 4.1.7 on 2023-03-23 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0006_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
