# Generated by Django 4.1.7 on 2023-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0007_chatroom_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
